### ISSUE TITLE
Create shell script to add new artifactory service account on artifactory for each user group with artifactory. 

### ISSUE THREAD

**Issue by bji129** [bji129/workplace#1]
**DevOps Coaching request**

**User story**

As a artifactory admin, I want to crate a shell script to create new application service accounts on artifactory for each user group that is extracted from nexus, so users from nexus can be easily onboarded.

**Tasks**

- [x] Shell script to read data from extracted csv file.
- [x] create new randomly generated service accounts with autogenerated passwords in Artifactory.

**Acceptance criteria**
- [x] new service accounts created and setup with proper permissions.
- [x] users should be able to login to service account and download the binaries.

**Comment by bji129** [comment]
Completed this task on April 13th 2018. new users created and tested the same.
